// @/lib/data.ts
export const products = [
  {
    id: 1,
    name: "Hedamo Organic Wild Honey",
    image: "https://images.pexels.com/photos/1386207/pexels-photo-1386207.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Food",
    description: "Pure wild honey harvested from organic farms in the mountains of New Zealand. Rich in antioxidants and natural enzymes.",
    price: 24.99,
    rating: 4.8,
    reviewCount: 3,
    features: ["Unprocessed", "Nutrient-rich", "Eco-friendly", "Raw"],
    nutrition: {
      calories: "70 per tbsp",
      sugar: "15g",
      protein: "0.1g",
      carbs: "17g",
      vitamins: "B, C",
    },
    traceability: {
      origin: "Manuka Forest, New Zealand",
      harvestDate: "September 2024",
      batchNumber: "MH-2024-09-15",
    },
    sustainability: [
      "Supports local beekeepers",
      "Plastic-free packaging",
      "Carbon neutral shipping",
      "Bee-friendly practices",
    ],
    reviews: [
      {
        user: "Sarah M.",
        rating: 5,
        comment: "Absolutely delicious! The taste is so pure and natural. Perfect for my morning tea.",
      },
      {
        user: "Mike R.",
        rating: 5,
        comment: "Best honey I've ever tasted. You can really taste the quality difference.",
      },
      {
        user: "Emma L.",
        rating: 4,
        comment: "Great product, though a bit pricey. The packaging is beautiful and sustainable.",
      },
    ],
  },
  {
    id: 2,
    name: "Pure Himalayan Sea Salt",
    image: "https://images.pexels.com/photos/1340116/pexels-photo-1340116.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Food",
    description: "Hand-mined pink salt from ancient sea beds in the Himalayas. Rich in minerals and perfect for cooking and wellness.",
    price: 18.99,
    rating: 4.7,
    reviewCount: 2,
    features: ["Hand-mined", "Mineral-rich", "Unrefined", "Ancient"],
    nutrition: {
      sodium: "590mg per tsp",
      minerals: "84 trace minerals",
      potassium: "2.8mg",
      calcium: "1.6mg",
      magnesium: "1.06mg",
    },
    traceability: {
      origin: "Khewra Salt Mine, Pakistan",
      harvestDate: "August 2024",
      batchNumber: "HS-2024-08-20",
    },
    sustainability: [
      "Traditional mining methods",
      "Supports local communities",
      "Minimal processing",
      "Reusable glass jar",
    ],
    reviews: [
      {
        user: "Chef David",
        rating: 5,
        comment: "This salt transforms every dish. The mineral complexity is incredible.",
      },
      {
        user: "Lisa K.",
        rating: 4,
        comment: "Love the taste and the beautiful pink color. Great for finishing dishes.",
      },
    ],
  },
  {
    id: 3,
    name: "Organic Turmeric Powder",
    image: "https://images.pexels.com/photos/4198015/pexels-photo-4198015.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Wellness",
    description: "Premium organic turmeric powder with high curcumin content. Sourced from sustainable farms in Kerala, India.",
    price: 16.99,
    rating: 4.9,
    reviewCount: 2,
    features: ["High curcumin", "Organic", "Anti-inflammatory", "Fresh ground"],
    nutrition: {
      curcumin: "3.14%",
      fiber: "2.6g per tbsp",
      iron: "4.12mg",
      potassium: "170mg",
      vitamin_C: "1.7mg",
    },
    traceability: {
      origin: "Kerala, India",
      harvestDate: "October 2024",
      batchNumber: "TU-2024-10-05",
    },
    sustainability: [
      "Organic farming practices",
      "Fair trade certified",
      "Biodegradable packaging",
      "Supports small farmers",
    ],
    reviews: [
      {
        user: "Dr. Patel",
        rating: 5,
        comment: "Excellent quality turmeric. The curcumin content is notably high.",
      },
      {
        user: "Yoga Instructor Jane",
        rating: 5,
        comment: "Perfect for my daily golden milk. So fresh and potent!",
      },
    ],
  },
  {
    id: 4,
    name: "Artisan Green Tea Blend",
    image: "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Wellness",
    description: "Premium loose-leaf green tea blend with jasmine flowers and mint. Grown in the high altitudes of Darjeeling.",
    price: 28.99,
    rating: 4.6,
    reviewCount: 2,
    features: ["Loose leaf", "High altitude", "Antioxidant rich", "Aromatic"],
    nutrition: {
      caffeine: "25mg per cup",
      antioxidants: "High EGCG",
      calories: "2 per cup",
      polyphenols: "Rich source",
      vitamin_K: "2.2mcg",
    },
    traceability: {
      origin: "Darjeeling, India",
      harvestDate: "March 2024",
      batchNumber: "GT-2024-03-12",
    },
    sustainability: [
      "Rainforest Alliance certified",
      "Compostable tea bags",
      "Water conservation practices",
      "Wildlife habitat protection",
    ],
    reviews: [
      {
        user: "Tea Enthusiast Mark",
        rating: 5,
        comment: "The most aromatic green tea I've ever had. Perfect balance of flavors.",
      },
      {
        user: "Sarah W.",
        rating: 4,
        comment: "Lovely blend, though I prefer stronger teas. Still excellent quality.",
      },
    ],
  },
  {
    id: 5,
    name: "Handcrafted Bamboo Cutting Board",
    image: "https://images.pexels.com/photos/4226881/pexels-photo-4226881.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Lifestyle",
    description: "Sustainable bamboo cutting board with antimicrobial properties. Handcrafted by skilled artisans in sustainable workshops.",
    price: 34.99,
    rating: 4.8,
    reviewCount: 2,
    features: ["Antimicrobial", "Sustainable", "Handcrafted", "Durable"],
    nutrition: {
      dimensions: "15x10x0.8 inches",
      weight: "1.2 lbs",
      material: "100% bamboo",
      finish: "Food-safe oil",
      care: "Hand wash only",
    },
    traceability: {
      origin: "Sustainable Bamboo Forests, Vietnam",
      harvestDate: "July 2024",
      batchNumber: "BB-2024-07-18",
    },
    sustainability: [
      "Rapidly renewable bamboo",
      "Zero waste production",
      "Artisan fair wages",
      "Plastic-free packaging",
    ],
    reviews: [
      {
        user: "Home Chef Alex",
        rating: 5,
        comment: "Beautiful craftsmanship and perfect size. Bamboo is naturally antimicrobial.",
      },
      {
        user: "Kitchen Pro Maria",
        rating: 5,
        comment: "This board has lasted over a year with daily use. Still looks great!",
      },
    ],
  },
  {
    id: 6,
    name: "Organic Rose Hip Face Serum",
    image: "https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Skincare",
    description: "Luxurious anti-aging serum with organic rose hip oil and vitamin C. Promotes skin regeneration and natural glow.",
    price: 42.99,
    rating: 4.7,
    reviewCount: 2,
    features: ["Anti-aging", "Vitamin C", "Organic", "Regenerating"],
    nutrition: {
      vitamin_C: "15%",
      vitamin_E: "Natural source",
      essential_acids: "Omega 3, 6, 9",
      antioxidants: "High concentration",
      volume: "30ml",
    },
    traceability: {
      origin: "Organic Farms, Chile",
      harvestDate: "April 2024",
      batchNumber: "RH-2024-04-22",
    },
    sustainability: [
      "Certified organic ingredients",
      "Recyclable glass bottle",
      "Cruelty-free testing",
      "Carbon-neutral production",
    ],
    reviews: [
      {
        user: "Skincare Expert Jenny",
        rating: 5,
        comment: "Amazing results after just 2 weeks. My skin looks more radiant and youthful.",
      },
      {
        user: "Beauty Blogger Lisa",
        rating: 4,
        comment: "Great serum, though the scent is quite strong. Results are definitely visible.",
      },
    ],
  },
];